-- MySQL Script generated by MySQL Workbench
-- Tue May  6 00:28:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wearther
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wearther` ;

-- -----------------------------------------------------
-- Schema wearther
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wearther` DEFAULT CHARACTER SET utf8 ;
USE `wearther` ;

-- -----------------------------------------------------
-- Table `wearther`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wearther`.`users` ;

CREATE TABLE IF NOT EXISTS `wearther`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(200) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `gender` VARCHAR(5) NULL,
  `birthday` DATE NULL,
  `profile_pic_url` VARCHAR(200) NULL,
  `photo_pic_url` VARCHAR(200) NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wearther`.`outfits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wearther`.`outfits` ;

CREATE TABLE IF NOT EXISTS `wearther`.`outfits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `styleTag` VARCHAR(30) NOT NULL,
  `occasionTag` VARCHAR(30) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `weather` VARCHAR(30) NOT NULL,
  `season` VARCHAR(10) NOT NULL,
  `image_url` VARCHAR(200) NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wearther`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wearther`.`posts` ;

CREATE TABLE IF NOT EXISTS `wearther`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `outfits_id` INT NOT NULL,
  `content` TEXT NULL,
  `media_url` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_users1_idx` (`users_id` ASC),
  INDEX `fk_posts_outfits1_idx` (`outfits_id` ASC),
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `wearther`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_outfits1`
    FOREIGN KEY (`outfits_id`)
    REFERENCES `wearther`.`outfits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wearther`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wearther`.`favorites` ;

CREATE TABLE IF NOT EXISTS `wearther`.`favorites` (
  `users_id` INT NOT NULL,
  `outfits_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`users_id`, `outfits_id`),
  INDEX `fk_favorites_outfits1_idx` (`outfits_id` ASC),
  INDEX `fk_favorites_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_favorites_outfits1`
    FOREIGN KEY (`outfits_id`)
    REFERENCES `wearther`.`outfits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorites_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `wearther`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wearther`.`likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wearther`.`likes` ;

CREATE TABLE IF NOT EXISTS `wearther`.`likes` (
  `users_id` INT NOT NULL,
  `posts_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  INDEX `fk_likes_users1_idx` (`users_id` ASC),
  INDEX `fk_likes_posts1_idx` (`posts_id` ASC),
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `wearther`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `wearther`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wearther`.`outfit_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wearther`.`outfit_item` ;

CREATE TABLE IF NOT EXISTS `wearther`.`outfit_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `outfits_id` INT NOT NULL,
  `category` VARCHAR(30) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_outfit_item_outfits1_idx` (`outfits_id` ASC),
  CONSTRAINT `fk_outfit_item_outfits1`
    FOREIGN KEY (`outfits_id`)
    REFERENCES `wearther`.`outfits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wearther`.`clothes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wearther`.`clothes` ;

CREATE TABLE IF NOT EXISTS `wearther`.`clothes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `category` VARCHAR(30) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `color` VARCHAR(10) NULL,
  `product_pic_url` VARCHAR(255) NOT NULL,
  `model_pic_url` VARCHAR(255) NULL,
  `link_url` VARCHAR(200) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wearther`.`tryons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wearther`.`tryons` ;

CREATE TABLE IF NOT EXISTS `wearther`.`tryons` (
  `users_id` INT NOT NULL,
  `clothes_id` INT NOT NULL,
  `category` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`users_id`, `clothes_id`),
  INDEX `fk_users_has_clothes_clothes1_idx` (`clothes_id` ASC),
  INDEX `fk_users_has_clothes_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_clothes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `wearther`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_clothes_clothes1`
    FOREIGN KEY (`clothes_id`)
    REFERENCES `wearther`.`clothes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wearther`.`related`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wearther`.`related` ;

CREATE TABLE IF NOT EXISTS `wearther`.`related` (
  `clothes_id` INT NOT NULL,
  `outfits_id` INT NOT NULL,
  PRIMARY KEY (`clothes_id`, `outfits_id`),
  INDEX `fk_clothes_has_outfits_outfits1_idx` (`outfits_id` ASC),
  INDEX `fk_clothes_has_outfits_clothes1_idx` (`clothes_id` ASC),
  CONSTRAINT `fk_clothes_has_outfits_clothes1`
    FOREIGN KEY (`clothes_id`)
    REFERENCES `wearther`.`clothes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clothes_has_outfits_outfits1`
    FOREIGN KEY (`outfits_id`)
    REFERENCES `wearther`.`outfits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
